Change order of initialization, fixes #1059
stevehipwell/helm-charts pull request #1062
Opened 2024-10-18 06:39 UTC by mreiche

```
Configuring Nexus3...
Waiting for Nexus...
Waiting for Nexus...
Waiting for Nexus...
Waiting for Nexus...
Configuring anonymous access...
Anonymous access configured.
Configuring blob stores...
Configuring repositories...
Repository 'osm-maps' configured.
Configuring roles...
Role 'nx-metrics' configured.
Role 'osm-reader' configured.
Role 'osm-writer' configured.
Configuring users...
User 'osm-reader' configured.
User 'osm-writer' configured.
Configuring scripts...
Script 'cleanup' updated.
Script 'task' updated.
Configuring cleanup policies...
Configuring tasks...
Nexus3 configured successfully!
```

2024-10-22 06:08 UTC, mreiche commented
> This looks good at first glance, and it looks like you've already tested it?
> 
> Could you add an entry to the CHANGELOG for this change?

The output above is from the tested container. I've updated the changelog but in the *Unreleased* section. Hope that fits.

2024-10-24 10:38 UTC, stevehipwell requested changes

2024-10-24 10:38 UTC, stevehipwell commented on charts/nexus3/CHANGELOG.md
> +- Changed the order of the initialization scripts to allow creating roles based on repository privileges (fixes #1059)
```suggestion
### Changed

- Changed the order of the initialization scripts to allow creating roles based on repository privileges. ([#1062](https://github.com/stevehipwell/helm-charts/pull/1062) _@mreiche_
```

If you want to reference the actual change this is the pattern to use.

2024-10-24 11:50 UTC, stevehipwell commented
@mreiche I'm having to do an emergency release of the chart so I'm going to make these changes directly. Thanks for your PR, FYI the scripts and cleanup blocks would also need moving up as repo config can refer to cleanup policies.

2024-10-24 12:16 UTC, closed without merging