Allow specific characters for ldap password
stevehipwell/helm-charts pull request #806
Opened 2023-10-12 15:03 UTC by djerfy

* Allow to use `"` and `/` in the LDAP password. By default sed return an error.

2023-10-17 07:04 UTC, stevehipwell requested changes
Thanks for the PR @djerfy, sorry I've been slow to reply. Could you also add a CHANGELOG entry for your change?

2023-10-17 07:43 UTC, djerfy commented
> Thanks for the PR @djerfy, sorry I've been slow to reply. Could you also add a CHANGELOG entry for your change?

Thanks! Update done

2023-10-17 12:59 UTC, stevehipwell commented
@djerfy sorry I don't think I was clear enough. The CHANGELOG entry should be `[UNRELEASED]` and the chart version shouldn't be changed as I'll release this with some other changes.

2023-10-17 15:24 UTC, djerfy commented
> @djerfy sorry I don't think I was clear enough. The CHANGELOG entry should be `[UNRELEASED]` and the chart version shouldn't be changed as I'll release this with some other changes.

Oops sorry

2023-10-18 07:10 UTC, stevehipwell commented
The workflow is failing due to a binary name change, I'm currently AFK but will fix this tomorrow and get it merged.

2023-10-20 11:57 UTC, stevehipwell commented
@djerfy can you squash your commits (or add another commit) to re-trigger the PR workflow?

2023-10-20 13:24 UTC, stevehipwell approved these changes
LGTM

2023-10-20 13:24 UTC, merged